CompileFlags:
  Add: [-Wall, -Wextra, -std=c++20] # use C++ 20 as default
Index:
  Background: Build                # automatically build index in background
Diagnostics:
  ClangTidy:
    Add: [
      cppcoreguidelines-*, 
      modernize-*, 
      readability-identifier-naming
    ]
